
spring:
  #  datasource:
#    url: jdbc:h2:mem:supplierdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:

# Use this for PostgreSQL (comment H2 out when using this)
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/productdb
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # change to 'create' to recreate tables
    show-sql: true

logging:
  level:
    com.lowes.matchxapp: DEBUG

  file:
    name: "logs/product.log"
