welcome:
  message: "Welcome to Spring Cloud Config (GIT) training :) WELCOME BACK!!!"
  
spring:
  datasource:
   url: jdbc:h2:mem:supplierdb
   driver-class-name: org.h2.Driver
   username: sa
   password:

