spring:
  application:
    name: supplier-service

  #  datasource:
  #     url: jdbc:postgresql://localhost:5432/training
  #     username: postgres
  #     password: postgres
  #     driver-class-name: org.postgresql.Driver
  #  jpa:
  #    hibernate:
  #      ddl-auto: update  # change to 'create' to recreate tables
  #    show-sql: true

  datasource:
    url: jdbc:h2:mem:supplierdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

h2:
  console:
    enabled: true
    path: /h2-console

server:
  port: 9091

logging:
  level:
    root: INFO
    com.lowes.matchxapp: DEBUG

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    register-with-eureka: true
  instance:
    prefer-ip-address: true





